Added CHP Bike Siren.
photonle/Photon pull request #130
Opened 2020-02-08 16:50 UTC by DatedGore

also changed the horn for both chp sirens

2020-02-08 18:51 UTC, creator2013 commented on lua/autorun/photon/library/sirens/anemolis_chp_bike.lua
> +		},
Tab spacing (╯‵□′)╯︵┻━┻

2020-02-08 18:52 UTC, creator2013 requested changes

2020-02-08 18:52 UTC, creator2013 commented on lua/autorun/photon/library/sirens/anemolis_chp_bike.lua
> +		},
Tab spacing (╯‵□′)╯︵┻━┻

2020-02-08 20:06 UTC, DatedGore commented on lua/autorun/photon/library/sirens/anemolis_chp_bike.lua
> +		},
🙄 and which one?

2020-02-08 20:09 UTC, DatedGore commented on lua/autorun/photon/library/sirens/anemolis_chp_bike.lua
> +		},
oh i see nvm

2020-02-08 20:12 UTC, DatedGore commented on lua/autorun/photon/library/sirens/anemolis_chp_bike.lua
> +		},
better?

2020-02-08 20:48 UTC, creator2013 commented on lua/autorun/photon/library/sirens/anemolis_chp_bike.lua
> +		},
No (line 10)

2020-02-11 16:57 UTC, creator2013 approved these changes

2020-02-11 17:37 UTC, merged