Update cl_emv_meta.lua
photonle/Photon pull request #158
Opened 2020-07-28 07:58 UTC by SentryGunMan

added attachment parenting and bone hiding to props and cleaned up some stupid ass code

2020-07-28 14:35 UTC, JoshPiper requested changes

2020-07-28 14:35 UTC, JoshPiper commented on lua/autorun/photon/cl_emv_meta.lua
> +				*/
Please use standard lua comments.

2020-07-28 14:35 UTC, JoshPiper commented on lua/autorun/photon/cl_emv_meta.lua
> +				--prop:DrawShadow( false )
Could be to handle the desync over time in some vehicles? Not 100% sure though.

2020-07-29 07:36 UTC, JoshPiper approved these changes

2020-07-29 07:36 UTC, JoshPiper approved these changes
Approved for theory, not tested ingame.

2020-07-31 11:29 UTC, SuperMighty1 approved these changes
gamer

2020-07-31 11:29 UTC, merged