Addition to the original TMD Siren
photonle/Photon pull request #63
Opened 2019-11-01 04:50 UTC by Officer-Pringle

Moved my siren wav into the original sound dir. and added the phaser tone to the original TMD Siren File as requested

2019-11-02 13:23 UTC, SuperMighty1 commented
Missing a comma at the end of the "PHSR" tone

2019-11-02 13:28 UTC, SuperMighty1 commented on lua/autorun/photon/library/emv_sirens.lua
> +			{Name = "PHSR", Sound = "emv/sirens/federal sig tm/pemv_tmjingle.wav", Icon = "phaser"} -- edit by pringle
Missing a comma at the end of the line.

2019-11-02 13:37 UTC, SuperMighty1 requested changes
Missing a comma at the end of the "PHSR" line.

2019-11-03 12:58 UTC, SuperMighty1 approved these changes
tasty

2019-11-03 18:31 UTC, Officer-Pringle commented
Cant believe I did such a noob thing

2019-11-07 11:30 UTC, merged